# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xci
# IP: The module: 'fifo512bit_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.srcs/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xci
# IP: The module: 'fifo512bit_1k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.gen/sources_1/ip/fifo512bit_1k/fifo512bit_1k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo512bit_1k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
