# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
# IP: The module: 'axis_dwidth_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/10m_lower_reverse_move_v2.3.gen/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/project_1.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
# IP: The module: 'axis_dwidth_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/vivado_prj/690t200w/HA-CJ-200w-test_v2.00/10m_lower_reverse_move_v2.3.gen/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
